### ISSUE TITLE
%%vskip has no effect

### ISSUE THREAD

**Issue by KuSi833** [abcjs-music/obsidian-plugin-abcjs#10]
The command `%%vskip 2cm` doesn't have any effect for me in Obsidian but does in an [online abc-music editor](https://www.abcjs.net/abcjs-editor.html).
Abcjs seems to support the command so could it be this library isn't using the most up to date version or am I doing something wrong?

**Comment by TilBlechschmidt** [comment]
I am not familiar with that particular command but the plugin is currently using the latest (officially released, non-beta) version of `abcjs`. So I am not too sure what is going on without further investigation. Might be some CSS wizardry done by Obsidian.

Unfortunately, I do not have the time to investigate further at the moment but if anybody has some input it is highly appreciated!

**Comment by KuSi833** [comment]
I tried comparing the svg elements both in Obsidian and on the online editor when changing `%%vskip 2cm` to `%%vskip 5cm`.
The svgs from the online editor do have differences in quite a few values but I don't know what they represent:
![image](https://user-images.githubusercontent.com/46829331/121039495-6c986e80-c7b1-11eb-9f83-e09704b6f812.png)

Meanwhile the two svgs in obsidian are identical:
![image](https://user-images.githubusercontent.com/46829331/121039619-8934a680-c7b1-11eb-9c6f-c52de96c3282.png)
I tried comparing an svg without %%vskip and one with and they are again identical.

So I assume there is no funky CSS business going on, the command seems to be ignored completely.

**Comment by alensiljak** [comment]
Hi, @KuSi833, I have tried with the latest Obsidian and the latest plugin/abcjs and the space at the top was added by `%%vskip 5cm`. 
Let me know, please, if this does not work for you.

Before:
![image](https://user-images.githubusercontent.com/462445/201049921-78a81dd3-7aac-454f-9636-bfbd4d9c6a25.png)

After:
![image](https://user-images.githubusercontent.com/462445/201049999-ce7be6fe-d409-47da-9d35-a8f0bd12609e.png)

**Comment by KuSi833** [comment]
Yes, can confirm it works now.
