### ISSUE TITLE
Update abcjs version

### ISSUE THREAD

**Issue by alensiljak** [abcjs-music/obsidian-plugin-abcjs#23]
Hi! Would it be possible to update the abcjs version?
I can send a pull request with this.

**Comment by stouf** [comment]
I think you can go ahead. The owner of this repository seems to be encouraging proactive actions 🙂

From the README:

> If you know your way around code, please consider contributing a pull request! I will gladly review and merge it.

**Comment by alensiljak** [comment]
Thanks for the tip, @stouf !
There are some interesting developments, in fact. We are in the process of joining this repo to the abcjs-music organization, where we will pool the effort in maintaining this and a few other music- and abc-related projects!
So an update might be coming soon.

**Comment by stouf** [comment]
> Thanks for the tip, @stouf ! There are some interesting developments, in fact. We are in the process of joining this repo to the abcjs-music organization, where we will pool the effort in maintaining this and a few other music- and abc-related projects! So an update might be coming soon.

Oh! That would be awesome! ♥️ I just started to use this plugin but I'm looking forward to that 🙂

**Comment by alensiljak** [comment]
Im' happy to see that! The organization is at https://github.com/abcjs-music and we have a Visual Studio Code extension already migrated there, with a few other projects in the pipeline, including the Obsidian plugin. Til was generous and happy with the idea to join the effort and relatively soon there will be a couple more people available to keep the projects up-to-date and provide additional features.

**Comment by TilBlechschmidt** [comment]
Thanks for proactively responding to issues @alensiljak! I second everything he said and will probably have some time in the coming days to get the migration through so we can harness the newfound momentum for the plugin 🙃

**Comment by alensiljak** [comment]
Finally done, with a small initial hiccup! The first release was more of a test drive for the release process but it also got the dependencies updated, mainly abcjs. The version will now follow the releases of abcjs, together with our [VSCode extension](https://github.com/abcjs-music/abcjs-vscode).
