### ISSUE TITLE
"octave" and "shift" keywords don't seem to affect score

### ISSUE THREAD

**Issue by chillinflute** [abcjs-music/obsidian-plugin-abcjs#28]
First of all, thank you so much for your hard work on this plugin; for a music student like me, it's been invaluable!

I'm writing my ABC notation up in EasyABC and importing it over to Obsidian. I've had to get used to making some tweaks on the transition as I think EasyABC lets me be a bit lazy about my code, which is fine; most things aren't too much of a hassle. However, one issue I can't seem to resolve is using the "octave" and "shift" keywords for my voices in bass clef: they don't seem to affect the score in the render. 

For context here a snippet of the code and the subsequent render in Easy Abc, and again in Obsidian:

```
X:1
T:In Nomine I  
C:William Byrd
M:C|
L:1/4
V:S clef=treble
V:A clef=treble
V:T clef=treble-8
V:B clef=bass octave=-2
%%score [ S A T B ]
%%barnumbers 8
K:F
% below the notes for each voice
V:S
Z2 | z2G2 | d3c | BAGF | EFE2 | D4 | 
V:A
[L:1/1] D | F | D | D | D | C | F |
V:T
z2G2 | d3c | BAG2- | G^F/E/F2 | G2D2 | A3G | FED2 | 
V:B
Z5 | z2A2 | d3c | 
V:S
z2d2 | f3e | dcB>c | dcfe- | e/d/d2"\#"c | d2z2 | ze2d | ecg2 | 
V:A
G | F | G | A | A- | A | A | c |
V:T
B4 | AAd>c | B>cde | f>edc | dfe2 | zd2c | dcf2 | e3d/c/ | 
V:B
BAG2 | d4 | G2g2 | f3a | fda2 | d2z2 | Z2 | 
% 16
V:S
f>gfe- | e/d/d2^c | d2z2 | zcdf | ec3/=B//c// B/A/ | cdeg | fe>dd- |
V:A
A | A | A/G/ | F | G- | G | A |
V:T
d3e | f>gfe- | e/d/d2"\#"c | dABA | ccdg | ed3/^c//d// c/"\="B/ | deaf |
V:B
zd2c | fda>g | fge2 | dfd2 | ceg2 | cge2 | dc2d |
% 23
V:S
d^c/=B/c2 | zef2 | ee2d | e2zA- | AG/A/GF | A2c2- | c2z2 | z2e2 | 
V:A
A | A | A | c | d | c | A | B | 
V:T
e4- | e2z2 | zef2 | e4 | Z | z2e2 | f3e | d>c B/A/G | 
V:B
a2A2- | AAd2 | cAd2 | A2a2 | b4 | a3g | fedc | BAG2 | 
```

<img width="414" alt="Screenshot 2022-11-25 at 11 05 58" src="https://user-images.githubusercontent.com/65876662/203972368-3b8d8e91-3632-41a9-86f6-13b84bc93042.png">

```
X:1
T:In Nomine I  
C:William Byrd
M:C|
L:1/4
%%score [ S A T B ]
V:S clef=treble
V:A clef=treble
V:T clef=treble-8
V:B clef=bass octave=-2
K:F
%%barnumbers 8
% below the notes for each voice
V:S
[L:1/4] z4 | z4 | z2G2 | d3c | BAGF | EFE2 | D4 | 
V:A
[L:1/1] D | F | D | D | D | C | F |
V:T
[L:1/4] z2G2 | d3c | BAG2- | G^F/E/F2 | G2D2 | A3G | FED2 | 
V:B
[L:1/4] z4 | z4 | z4 | z4 | z4 | z2A2 | d3c | 
V:S
[L:1/4] z2d2 | f3e | dcB>c | dcfe- | e/d/d2"\#"c | d2z2 | ze2d | ecg2 | 
V:A
[L:1/1] G | F | G | A | A- | A | A | c |
V:T
[L:1/4] B4 | AAd>c | B>cde | f>edc | dfe2 | zd2c | dcf2 | e3d/c/ | 
V:B
[L:1/4] BAG2 | d4 | G2g2 | f3a | fda2 | d2z2 | z4 | z4 |
% 16
V:S
[L:1/4] f>gfe- | e/d/d2^c | d2z2 | zcdf | ec3/=B//c// B/A/ | cdeg | fe>dd- |
V:A
[L:1/1] A | A | A/G/ | F | G- | G | A |
V:T
[L:1/4] d3e | f>gfe- | e/d/d2"\#"c | dABA | ccdg | ed3/^c//d// c/"\="B/ | deaf |
V:B
[L:1/4] zd2c | fda>g | fge2 | dfd2 | ceg2 | cge2 | dc2d |
% 23
V:S
[L:1/4] d^c/=B/c2 | zef2 | ee2d | e2zA- | AG/A/GF | A2c2- | c2z2 | z2e2 | 
V:A
[L:1/1] A | A | A | c | d | c | A | B | 
V:T
[L:1/4] e4- | e2z2 | zef2 | e4 | z4 | z2e2 | f3e | d>c B/A/G | 
V:B
[L:1/4] a2A2- | AAd2 | cAd2 | A2a2 | b4 | a3g | fedc | BAG2 |
 ```

<img width="383" alt="Screenshot 2022-11-25 at 11 08 15" src="https://user-images.githubusercontent.com/65876662/203972817-dc9d281e-3bae-4a38-9454-aa1e8c88158c.png">

I have thus far tried putting in different positions in the preamble, square bracketing the relevant areas, and reinstating `[V:octave=-2]` much like I have `[L:1/4]`. No joy so far. Any ideas are hugely appreciated.

**Comment by TilBlechschmidt** [comment]
Hey @chillinflute, thanks for the kind words and a happy new year!

This looks like an issue with the underlying abc.js library to me of which this plugin is just a thin wrapper. Since it has been a while since this was posted, you might have more luck creating an issue over in the [paulrosen/abcjs](https://github.com/paulrosen/abcjs/issues) repo (the place where the actual issue behind this likely comes from).

**Comment by burgbach** [comment]
I think abcjs 6.2.0 adds support for octave (I don't know about shift), see https://github.com/paulrosen/abcjs/pull/823/commits
Could you do a new release based on it ?

**Comment by alensiljak** [comment]
@burgbach, thanks for the tip. I've just pushed the 1.3.0 update.

**Comment by burgbach** [comment]
@alensiljak, thanks for the lightning fast release, I can confirm the octave feature now works :-)

**Comment by alensiljak** [comment]
Awesome!
If @chillinflute, or anyone else, could confirm what the current state with the `shift` keyword is, that would be great.
