### ISSUE TITLE
Default behaviour does not render the background

### ISSUE THREAD

**Issue by dotkiddo** [abcjs-music/obsidian-plugin-abcjs#3]
Here is an example of what the render looks like when using obsidians translucent effects:

![image](https://user-images.githubusercontent.com/14318808/102477322-de92c500-4064-11eb-9909-93c91230ee26.png)

The notes are rendered, but the background is left as ~whitespace~ alphaspace

Solution options: 
1. Allow the user to specify plugin preferences. 
    I see there was a previously opened issue re. font colours, perhaps plugin settings could be developed to allow the user to select the colours & opacity/translucency for font and background (2 birds 1 stone)
    More effort, gives user more control.

2. or Render white instead of alpha.
    Quick fix, user has no say.

**Comment by TilBlechschmidt** [comment]
Hi there!

I'm currently pretty busy with my Thesis so if you are up for the challenge I'd appreciate a PR. Rendering a solid background might visually collide with users defining their own backgrounds (no idea if anybody uses patterns or pictures) and would have to take dark mode into account.

The best option is probably to add some settings which apply dynamic styles with sensible defaults (e.g. choose between: no background, automatic background as in white/black, fixed color & opacity background).

If you don't have the time I'll probably have some time early next month.

**Comment by alensiljak** [comment]
Hi, @dotkiddo, have you tried customizing the background using some of the ways recommended for Obsidian, i.e. https://forum.obsidian.md/t/way-to-change-background-color-while-keeping-a-theme/20856 ?
