### ISSUE TITLE
Sharps and Flats 

### ISSUE THREAD

**Issue by dvansoye** [abcjs-music/obsidian-plugin-abcjs#38]
Sorry. Must of missed it. But how do you notate sharps and flats? I didn't see any examples of this in the documentation.

**Comment by alensiljak** [comment]
Here is a direct answer: http://music.stackexchange.com/questions/45940/ddg#45941

but I'm sure it is somewhere in the ABC notation specs.
Another useful resource is the wiki:
https://abcwiki.org/abc:syntax

**Comment by alensiljak** [comment]
Please reopen if this does not answer your question.
