### ISSUE TITLE
Option to use Latin notation

### ISSUE THREAD

**Issue by javiavid** [abcjs-music/obsidian-plugin-abcjs#39]
Would an option be possible in the configuration to use Latin notation (Do Re Mi..)?
Maybe to make it simpler instead of writing "DoReSolDo" you could use only the first letter of the note "DRSD"

**Comment by javiavid** [comment]
Thank you very much for your answer.

My idea was to be able to use another type of musical notation instead of ABC. I understand that it is the most standard in the English language, but at least in my country the Latin notation is more standard.
https://en.wikipedia.org/wiki/Solf%C3%A8ge

I don't know if there is a project or plugin that does what I'm looking for, but I haven't found it.

**Comment by alensiljak** [comment]
It is a lot of work to implement something like that, and a lot of moving parts. It is always a balance of what is available and how much time and effort it takes to create what you need in the end.
It is most likely easier to learn the ABC notation and use all the existing tools and libraries than to come up with a new own system for the same output. ;)
