### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [abcjs-music/obsidian-plugin-abcjs#46]
Hi there

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason:
- missing `manifest.json` file in the root of the repo

We will remove this plugin from the community plugins if this issue is not fixed within 30 days.

- The Obsidian Team

**Comment by alensiljak** [comment]
Result of #44

**Comment by alensiljak** [comment]
Reverted the latest changes.
