### ISSUE TITLE
Color noteheads (via custom css style)

### ISSUE THREAD

**Issue by danielparton** [abcjs-music/obsidian-plugin-abcjs#52]
Hi, this is a wonderful extension! Thank you for your work on it!

I have a 4-voice choral piece for which I'd like to specify a color (e.g. blue or red) for all the notes in one specified voice. The abcjs [docs](https://paulrosen.github.io/abcjs/visual/classes.html#class-names) show that it should be possible to set `add_classes: true` in the abcjsParams header, and then supply a custom css style for the .abcjs-v0 class. I can do the former, but is there a way to do supply a custom css style within the code block in an Obsidian note? I've included my code block below for reference.

Note that for different pieces, I would want to color different voices, and choose different colors. So I think this would need to be something that is specified in the code block that I enter into an Obsidian note.

Here is the [abcjs example configurator](https://configurator.abcjs.net/classes/) for classes.

```
{
  "responsive": null,
  "staffwidth": 940,
  "wrap": {
      "minSpacing": 1.0,
      "maxSpacing": 2.7,
      "preferredMeasuresPerLine": 8
  },
  "add_classes": true,
  "scale": 0.8
}
---
X:1
V:T1 clef=treble name="Soprano"
V:T2 clef=treble name="Alto"
V:B1 clef=treble-8 name="Tenor" octave=+1
V:B2 clef=bass name="Bass"
L:1/4
M:C
K:Bm
P:#50
[V:T1]d2  f   d   |e2  c2  |^A2 B  d  |c4  |
[V:T2]F2  F   F   |B2  G2  |F2  F  F  |F4  |
[V:B1]B,2 C   B,  |B,2 E2  |C2  B, B, |^A,4|
[V:B2]B,,2^A,,B,, |G,2 E,2 |F,2 D, B,,|F,4 |
[V:T1]B2  ^A  B   |G   g   e   c   |
[V:T2]F2  E   F   |E2      B   G   |
[V:B1]B,2 C   B,  |B,2     B,  C   |
[V:B2]D,2 C,  D,  |E,2     G,  E,  |
[V:T1]^A  B   c   A   |B4  ||
[V:T2]F   F   G   F   |F4  ||
[V:B1]C   B,  C   C   |D4  ||
[V:B2]F,  D,  E,  F,  |B,,4||
```

**Comment by paulrosen** [comment]
There's not currently a way to specify it from within abcjs. That doesn't matter when running this in a browser since you can add css to the page. It looks like there may be some control of this in Obsidian from a quick search, but I'm not sure.

Can you do it with frontmatter:
```
---
cssclass: "voice-color"
---
```
 Or am I reading that wrong?

**Comment by danielparton** [comment]
Thanks so much - I got this working!

For reference, I put the following at the top of the Obsidian note (frontmatter, which now uses `cssclasses` after deprecating `cssclass`):

```
---
cssclasses:
  - challan-soprano
---
```

And I put this in a CSS snippet

```
.challan-soprano svg .abcjs-v0 {
  fill:blue;
}
```

Would be nice if there was a way to do this on a per-codeblock basis. There's an extension [Markdown Attributes](https://github.com/javalent/markdown-attributes) which is designed to do that, but unfortunately it seems to be no longer actively developed, and it didn't seem to work with a codeblock.
But for now, it's great to be able to do this with frontmatter.
